DECLARE @value VARCHAR(50)
SET @value = '4305191D-3CD6-4A72-B221-FF61CAC853C0' -- INSERT PATIENT_UUID

select ATSI, AGEATEXTRACTION, GENDER_CODE from DB_Medical_Director_V3_10_5_ePBRN_PATIENT_V1
where Patient_UUID = @value

SELECT CONDITION, STAMP_DATETIME as DATE from DB_Medical_Director_V3_10_5_ePBRN_HISTORY

where Patient_UUID = @value

UNION

SELECT REASON as CONDITION, DIAGNOSIS_DATE as DATE from DB_Medical_Director_V3_10_5_ePBRN_DIAGNOSIS
where Patient_UUID = @value

UNION

SELECT REASON as CONDITION, VISIT_DATE as DATE from DB_Medical_Director_V3_10_5_ePBRN_MD_PROGRESS
where Patient_UUID = @value

SELECT DRUG_NO, REASON, DOSE, AMT_PREF_TERM, O.MD_SOURCE_AMT, O.ATC_CODE OMOP_ATC, B.ATC_CODE PBS_ATC FROM DB_Medical_Director_V3_10_5_ePBRN_PRESCRIPTION_V1 P
inner JOIN MD_AMT A ON P.DRUG_NO = A.MD_DRUG_NO
Full outer JOIN OMOP_MD_ATC_AMT_V3 O ON P.DRUG_NO = O.MD_DRUG_NO
Full outer JOIN PBS_MD_ATC_AMT b ON P.DRUG_NO = b.MD_DRUG_NO

where Patient_UUID = @value
group by REASON, AMT_PREF_TERM, ATCCODE, DOSE, DRUG_NO, O.ATC_CODE, B.ATC_CODE, O.MD_SOURCE_AMT

union 

SELECT DRUG_NO, REASON, DOSE, AMT_PREF_TERM, O.MD_SOURCE_AMT, O.ATC_CODE OMOP_ATC, B.ATC_CODE PBS_ATC FROM DB_Medical_Director_V3_10_5_ePBRN_REPEAT_PRESCRIPTION_V1 p
inner JOIN MD_AMT A ON P.DRUG_NO = A.MD_DRUG_NO
Full outer JOIN OMOP_MD_ATC_AMT_V3 O ON P.DRUG_NO = O.MD_DRUG_NO
Full outer JOIN PBS_MD_ATC_AMT b ON P.DRUG_NO = b.MD_DRUG_NO

where Patient_UUID = @value
group by REASON, AMT_PREF_TERM, ATCCODE, DOSE, DRUG_NO, O.ATC_CODE, B.ATC_CODE, O.MD_SOURCE_AMT

select TEST_NAME,RESULT, UNITS, NORMAL_RANGE from DB_Medical_Director_V3_10_5_ePBRN_PATHOLOGY
where Patient_UUID = @value


